"""update device model

Revision ID: a3d0829c09f1
Revises: bc9dd0c9fa6d
Create Date: 2022-11-12 14:45:19.404289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d0829c09f1'
down_revision = 'bc9dd0c9fa6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_device', sa.Column('device_code', sa.String(length=8), nullable=False))
    op.drop_constraint('user_device_device_id_fkey', 'user_device', type_='foreignkey')
    op.create_foreign_key(None, 'user_device', 'device', ['device_code'], ['code'])
    op.drop_column('user_device', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_device', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_device', type_='foreignkey')
    op.create_foreign_key('user_device_device_id_fkey', 'user_device', 'device', ['device_id'], ['id'])
    op.drop_column('user_device', 'device_code')
    # ### end Alembic commands ###
