"""Added more model

Revision ID: bc9dd0c9fa6d
Revises: fd980dc5f437
Create Date: 2022-11-12 14:37:39.225211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9dd0c9fa6d'
down_revision = 'fd980dc5f437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_manufacture', sa.DateTime(), nullable=False),
    sa.Column('place_of_manufacture', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_code'), 'device', ['code'], unique=True)
    op.create_index(op.f('ix_device_device_name'), 'device', ['device_name'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('device_code', sa.String(length=8), nullable=False),
    sa.Column('data', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['device_code'], ['device.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_device',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_device')
    op.drop_table('record')
    op.drop_index(op.f('ix_device_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_code'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
